config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activiteiten
  get 'pages/info'

	root to: redirect('/activiteiten')
  	resources :activiteiten
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activiteit.rb
class Activiteit < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activiteiten_controller.rb
class ActiviteitenController < ApplicationController
  before_action :set_activiteit, only: [:show, :edit, :update, :destroy]

  # GET /activiteiten
  # GET /activiteiten.json
  def index
    @activiteiten = Activiteit.all
  end

  # GET /activiteiten/1
  # GET /activiteiten/1.json
  def show
  end

  # GET /activiteiten/new
  def new
    @activiteit = Activiteit.new
  end

  # GET /activiteiten/1/edit
  def edit
  end

  # POST /activiteiten
  # POST /activiteiten.json
  def create
    @activiteit = Activiteit.new(activiteit_params)

    respond_to do |format|
      if @activiteit.save
        format.html { redirect_to @activiteit, notice: 'Activiteit was successfully created.' }
        format.json { render :show, status: :created, location: @activiteit }
      else
        format.html { render :new }
        format.json { render json: @activiteit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activiteiten/1
  # PATCH/PUT /activiteiten/1.json
  def update
    respond_to do |format|
      if @activiteit.update(activiteit_params)
        format.html { redirect_to @activiteit, notice: 'Activiteit was successfully updated.' }
        format.json { render :show, status: :ok, location: @activiteit }
      else
        format.html { render :edit }
        format.json { render json: @activiteit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activiteiten/1
  # DELETE /activiteiten/1.json
  def destroy
    @activiteit.destroy
    respond_to do |format|
      format.html { redirect_to activiteiten_url, notice: 'Activiteit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activiteit
      @activiteit = Activiteit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activiteit_params
      params.require(:activiteit).permit(:naam, :beschrijving, :afbeelding)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/activiteiten_helper.rb
module ActiviteitenHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activiteiten/_form.html.erb
<%= form_with(model: activiteit, local: true) do |form| %>
  <% if activiteit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activiteit.errors.count, "error") %> prohibited this activiteit from being saved:</h2>

      <ul>
      <% activiteit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :naam %>
    <%= form.text_field :naam, id: :activiteit_naam %>
  </div>

  <div class="field">
    <%= form.label :beschrijving %>
    <%= form.text_area :beschrijving, id: :activiteit_beschrijving %>
  </div>

  <div class="field">
    <%= form.label :afbeelding %>
    <%= form.text_field :afbeelding, id: :activiteit_afbeelding %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activiteiten/edit.html.erb
<h1>Editing Activiteit</h1>

<%= render 'form', activiteit: @activiteit %>

<%= link_to 'Show', @activiteit %> |
<%= link_to 'Back', activiteiten_path %>

app/views/activiteiten/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activiteiten</h1>

<table>
  <thead>
    <tr>
      <th>Naam</th>
      <th>Beschrijving</th>
      <th>Afbeelding</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activiteiten.each do |activiteit| %>
      <tr>
        <td><%= activiteit.naam %></td>
        <td><%= activiteit.beschrijving %></td>
        <td><%= activiteit.afbeelding %></td>
        <td><%= link_to 'Show', activiteit %></td>
        <td><%= link_to 'Edit', edit_activiteit_path(activiteit) %></td>
        <td><%= link_to 'Destroy', activiteit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activiteit', new_activiteit_path %>

app/views/activiteiten/new.html.erb
<h1>New Activiteit</h1>

<%= render 'form', activiteit: @activiteit %>

<%= link_to 'Back', activiteiten_path %>

app/views/activiteiten/show.html.erb
<p>
  <strong>Naam:</strong>
  <%= @activiteit.naam %>
</p>

<p>
  <strong>Beschrijving:</strong>
  <%= @activiteit.beschrijving %>
</p>

<p>
  <strong>Afbeelding:</strong>
  <%= @activiteit.afbeelding %>
</p>

<%= link_to 'Edit', edit_activiteit_path(@activiteit) %> |
<%= link_to 'Back', activiteiten_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <footer>
    <div class="container">
      Rails Girls <%= Time.now.year %>
    </div>
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  
  <body>
  	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">A.S.V. Prometheus</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/activiteiten">Activiteiten</a></li>
        
      </ul>
      
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% if current_user.rights == true%> 
          <strong>Rights <%current_user.rights%></strong>
          <%else%>
        <%end%>

      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>

    </div>
  </div>
</nav>

    <div class="container">
    	<% if notice %>
    	  <p class="alert alert-success"><%= notice %></p>
    	<% end %>
    	<% if alert %>
    	  <p class="alert alert-danger"><%= alert %></p>
    	<% end %>
  		<%= yield %>
	</div>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>